language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_6b30fc69e25b_key -iv $encrypted_6b30fc69e25b_iv -in applicaction.properties.enc -out src/main/resources/applicaction.properties -d
